name: 'credit_default_predict' 
channels:
  - conda-forge
  - defaults
dependencies:
- docopt=0.6.2
- ipykernel=6.15
- ipython=7.15
- selenium=4.3.0
- matplotlib=3.2.2
- scikit-learn=1.1.3
- pandas=1.4.3
- requests=2.24.0
- pip=22.2.2
- pip:
  - joblib==1.1.0
  - mglearn==0.1.9
  - psutil==5.7.2
  - openpyxl==3.0.0
  - xlrd==2.0.1
  - xlwt==1.3.0
  - seaborn==0.12.1
